//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC
    {
        public int Id { get; set; }
        public Nullable<System.Guid> MusteriID { get; set; }
        public string KartIsim { get; set; }
        public string KartNo { get; set; }
        public System.DateTime SonKulTar { get; set; }
        public string CVCKodu { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
