//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public int Id { get; set; }
        public Nullable<System.Guid> MusteriID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Baslik { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
