//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTicaret.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sati()
        {
            this.SiparisDetays = new HashSet<SiparisDetay>();
        }
    
        public int Id { get; set; }
        public System.Guid MusteriID { get; set; }
        public System.DateTime SatisTarihi { get; set; }
        public decimal ToplamTutar { get; set; }
        public bool SepetteMi { get; set; }
        public Nullable<int> KargoID { get; set; }
        public Nullable<int> SiparisDurumID { get; set; }
        public Nullable<int> KargoTakipNo { get; set; }
        public Nullable<int> OdemeDurumID { get; set; }
        public Nullable<int> MusteriAdresID { get; set; }
    
        public virtual Kargo Kargo { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual OdemeDurum OdemeDurum { get; set; }
        public virtual SiparisDurum SiparisDurum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetays { get; set; }
        public virtual MusteriAdre MusteriAdre { get; set; }
    }
}
